Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.network "private_network", ip: "192.168.56.10"
    config.vm.network "forwarded_port", guest: 5000, host: 5000
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024" 
        vb.cpus = 1 
        vb.name = "devsecops-vm"
    end
    config.ssh.insert_key = false
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y python3 python3-pip
        apt-get install -y docker.io
        usermod -aG docker vagrant
        mkdir -p /etc/docker
        echo '{"insecure-registries": ["localhost:5000", "192.168.56.10:5000", "127.0.0.1:5000"] }' > /etc/docker/daemon.json
        systemctl restart docker
        chmod 666 /var/run/docker.sock
    SHELL
end
    