- name: Установка Python
  hosts: web
  become: yes
  tasks:
    - name: Установить Python3 и pip
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: latest
        update_cache: yes
